Add honeycomb event
replayio/replay-cli pull request #431
Opened 2024-05-03 21:57 UTC by jasonLaster

This adds a `sendEvent` method for tracking errors in honeycomb.

2024-05-03 22:03 UTC, bvaughn requested changes
Let's talk on Monday. I'd rather get consensus from the TT team that this is the right place to send the data, and the right data to be sending (`stderr` may contain a lot of noise, and it may not contain useful info that's in a crashpad file)

2024-05-03 22:12 UTC, jasonLaster commented
Yep - will defer to @jcmorrow and TT

2024-05-05 14:30 UTC, bvaughn commented on packages/replayio/src/utils/telemetry.ts
> +}
This method isn't being used:
```suggestion
```

2024-05-05 14:30 UTC, bvaughn commented on packages/replayio/src/utils/telemetry.ts
> +}
This method isn't being used:
```suggestion
```

2024-05-05 14:30 UTC, bvaughn commented on packages/replayio/src/commands/record.ts
> +        });
I think we'd probably want to send more info along with such a crash– the runtime build id for example, and potentially the CLI package version as well.

There may also be [crash dump files](https://chromium.googlesource.com/crashpad/crashpad) with data that isn't present in `stderr`. Chromium puts them [here](https://www.chromium.org/developers/crash-reports/#generating-crash-dumps-locally) by default but I'm not sure where Replay writes them. (This is something I left a question about on PRO-235/TT-983.)

2024-06-03 12:35 UTC, closed without merging

2024-06-03 12:35 UTC, bvaughn commented
Closing this PR since it's old and stale. Rebase and re-open if you'd like us to review and consider!